rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
script: "bundle exec rake test"
