rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  # these will fail because Ruby 1.8 doesn't support ordered hashes
  #- rbx-18mode
  #- jruby-18mode
  #- 1.8.7
  #- ree
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode # this currently fails because of rmagick. see https://github.com/linkedin/archetype/issues/5
    - rvm: rbx-18mode
    - rvm: ree
script: "bundle exec rake test"
