rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
  - ree
env:
  - JRUBY_OPTS="-Xcext.enabled=true -J-Xmx1024m" JVM_OPTS="-XX:-UseGCOverheadLimit"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_script:
  - ulimit -S -s unlimited
  - ulimit -a
script: "bundle exec rake test"
