# general configs
exclude   : ["README.md", "Rakefile", "changelog.md", "LICENSE", "Procfile", "Gemfile", "config.rb"]
auto      : true
pygments  : true
# Maruku doesn't play nicely with scss syntax in pygments
markdown  : rdiscount
# site info
title     : Archetype CSS
tagline   : UI pattern and component library...
# permalinks
permalink : /:categories/:title
# author
author :
  name    : LinkedIn
  github  : eoneill
  twitter : ArchetypeCSS
# The production_url is only used when full-domain names are needed such as sitemap.txt 
production_url : http://www.archetypecss.com

## custom configs
# copyright notice
copyright :
  holder  : LinkedIn Corporation
  year    : 2012
# asset management
assets :
  cacheBurst : true
  stylesheets :
    - { name: main }
  vendor :
    scripts :
      jQuery :
        version : 1.8.2
archetype :
  version : 0.0.1.pre.2
lang      : en
# git info
git :
  account : eoneill
  repo    : archetype
# footer
footer :
  links : 
    - {title : GitHub, git : true, url : '' }
    - {title : Issue Tracker, git : true, url : 'issues?state=open' }
    - {title : CHANGELOG, git : true, url : 'blob/master/CHANGELOG.md' }
    - {title : Contributing, git : true, url : 'blob/master/CONTRIBUTING.md' }

# all links will be namespaced by BASE_PATH if defined
BASE_PATH : false

# By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
# ex: [BASE_PATH]/assets/
#
# Override this by defining an absolute path to assets here.
# ex: 
#   http://s3.amazonaws.com/yoursite/themes/watermelon/assets
ASSET_PATH : false

# some native pages
archive_path    : /archive.html
categories_path : /categories.html
tags_path       : /tags.html

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
comments :
  provider : livefyre
  livefyre :
    site_id : 313052

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-1545927-5'

search :
  provider : tapir
  tapir :
    token : 506beaeb3f61b03a8b000229
