source 'https://rubygems.org'

gem 'jekyll', '~> 1.0.0'
gem 'archetype', '0.0.1.pre.3.6ed259b'
gem 'compass'
gem 'foreman'
gem 'rake'
gem 'rdiscount'
gem 'jammit'
gem 'guard-jammit'
gem 'rb-fsevent', '~> 0.9.1'
